[2025-02-21T08:18:14.738+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-21T08:18:15.034+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.consolidate_data scheduled__2025-02-20T00:00:00+00:00 [queued]>
[2025-02-21T08:18:16.517+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.consolidate_data scheduled__2025-02-20T00:00:00+00:00 [queued]>
[2025-02-21T08:18:16.526+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-21T08:18:16.675+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): consolidate_data> on 2025-02-20 00:00:00+00:00
[2025-02-21T08:18:16.729+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=98) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-21T08:18:16.768+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'consolidate_data', 'scheduled__2025-02-20T00:00:00+00:00', '--job-id', '1129', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpdkqr9kcj']
[2025-02-21T08:18:16.778+0000] {standard_task_runner.py:72} INFO - Started process 100 to run task
[2025-02-21T08:18:16.783+0000] {standard_task_runner.py:105} INFO - Job 1129: Subtask consolidate_data
[2025-02-21T08:18:17.312+0000] {task_command.py:467} INFO - Running <TaskInstance: pipeline.consolidate_data scheduled__2025-02-20T00:00:00+00:00 [running]> on host 5f8091faf500
[2025-02-21T08:18:20.629+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='consolidate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-20T00:00:00+00:00'
[2025-02-21T08:18:20.652+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-21T08:18:20.659+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-21T08:18:20.669+0000] {logging_mixin.py:190} INFO - Current task name:consolidate_data state:running start_date:2025-02-21 08:18:15.039213+00:00
[2025-02-21T08:18:20.675+0000] {logging_mixin.py:190} INFO - Dag name:pipeline and current dag run status:running
[2025-02-21T08:18:20.695+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-21T08:18:20.727+0000] {logging_mixin.py:190} WARNING - --- Logging error ---
[2025-02-21T08:18:20.739+0000] {logging_mixin.py:190} WARNING - Traceback (most recent call last):
[2025-02-21T08:18:20.743+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
[2025-02-21T08:18:20.744+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
[2025-02-21T08:18:20.752+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
[2025-02-21T08:18:20.754+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
[2025-02-21T08:18:20.800+0000] {logging_mixin.py:190} WARNING - TypeError: not all arguments converted during string formatting
[2025-02-21T08:18:20.801+0000] {logging_mixin.py:190} WARNING - Call stack:
[2025-02-21T08:18:21.189+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2025-02-21T08:18:21.201+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/__main__.py", line 62, in main
    args.func(args)
[2025-02-21T08:18:21.215+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2025-02-21T08:18:21.243+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
[2025-02-21T08:18:21.305+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 64, in wrapper
    providers_configuration_loaded(func)(*args, **kwargs)
[2025-02-21T08:18:21.314+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2025-02-21T08:18:21.319+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 237, in worker
    _run_command_with_daemon_option(
[2025-02-21T08:18:21.322+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 50, in _run_command_with_daemon_option
    run_command_with_daemon_option(*args, **kwargs)
[2025-02-21T08:18:21.324+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
    callback()
[2025-02-21T08:18:21.335+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 230, in run_celery_worker
    celery_app.worker_main(options)
[2025-02-21T08:18:21.338+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
[2025-02-21T08:18:21.343+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
[2025-02-21T08:18:21.351+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
[2025-02-21T08:18:21.358+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2025-02-21T08:18:21.367+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2025-02-21T08:18:21.379+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
[2025-02-21T08:18:21.381+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2025-02-21T08:18:21.389+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/bin/base.py", line 135, in caller
    return f(ctx, *args, **kwargs)
[2025-02-21T08:18:21.394+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2025-02-21T08:18:21.400+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2025-02-21T08:18:21.412+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2025-02-21T08:18:21.428+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2025-02-21T08:18:21.430+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2025-02-21T08:18:21.444+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2025-02-21T08:18:21.449+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2025-02-21T08:18:21.461+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
[2025-02-21T08:18:21.464+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2025-02-21T08:18:21.470+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
[2025-02-21T08:18:21.491+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2025-02-21T08:18:21.495+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2025-02-21T08:18:21.496+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2025-02-21T08:18:21.499+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2025-02-21T08:18:21.503+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2025-02-21T08:18:21.505+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2025-02-21T08:18:21.507+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
[2025-02-21T08:18:21.511+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2025-02-21T08:18:21.521+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 651, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2025-02-21T08:18:21.531+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
[2025-02-21T08:18:21.541+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
[2025-02-21T08:18:21.561+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 139, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2025-02-21T08:18:21.569+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 171, in _execute_in_fork
    args.func(args)
[2025-02-21T08:18:21.580+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2025-02-21T08:18:21.591+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
[2025-02-21T08:18:21.615+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2025-02-21T08:18:21.623+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2025-02-21T08:18:21.633+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2025-02-21T08:18:21.643+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
[2025-02-21T08:18:21.649+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2025-02-21T08:18:21.660+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
[2025-02-21T08:18:21.671+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
[2025-02-21T08:18:21.672+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
[2025-02-21T08:18:21.674+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2025-02-21T08:18:21.677+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2025-02-21T08:18:21.682+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
[2025-02-21T08:18:21.683+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2025-02-21T08:18:21.700+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2025-02-21T08:18:21.716+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
[2025-02-21T08:18:21.736+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
[2025-02-21T08:18:21.742+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
[2025-02-21T08:18:21.759+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
[2025-02-21T08:18:21.761+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2025-02-21T08:18:21.776+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
[2025-02-21T08:18:21.780+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
[2025-02-21T08:18:21.784+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
[2025-02-21T08:18:21.810+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
[2025-02-21T08:18:21.816+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
[2025-02-21T08:18:21.821+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
[2025-02-21T08:18:21.831+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
[2025-02-21T08:18:21.844+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
[2025-02-21T08:18:21.868+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
[2025-02-21T08:18:21.873+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
[2025-02-21T08:18:21.880+0000] {logging_mixin.py:190} WARNING -   File "/opt/***/dags/operators/prepare_data/consolidate_date.py", line 10, in consolidate_data
    logger.info(df1, df2, df3)
[2025-02-21T08:18:21.897+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1539, in info
    self._log(INFO, msg, args, **kwargs)
[2025-02-21T08:18:21.908+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
[2025-02-21T08:18:21.917+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
[2025-02-21T08:18:21.922+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
[2025-02-21T08:18:21.927+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
[2025-02-21T08:18:21.938+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/log/file_task_handler.py", line 277, in emit
    self.handler.emit(record)
[2025-02-21T08:18:21.992+0000] {logging_mixin.py:190} WARNING - Message:                                              comment drag_name
0  Достоинства: ничего\nНедостатки: почитал полож...  Афобазол
1  Достоинства: Препарат рабочий, нервы успокаива...  Афобазол
2  Достоинства: Их нет!\nНедостатки: Не помогает ...  Афобазол
3  После потери близкого человека думала сойду с ...   Авиандр
4  Пробовала разные подобные препараты, но из все...   Авиандр
5  Достоинства: Очень помог\nНедостатки: Нет\nКом...   Авиандр
Arguments: (                                              comment     drag_name
0   Достоинства: Доступная цена, легко найти в люб...      Афобазол
1   Достоинства: Таблетка небольшая по форме, удоб...      Афобазол
2   Достоинства: Самое главное - действительно пом...      Афобазол
3   Хороший отечественный препарат, предназначенны...      Афобазол
4   Каждый год осенью мир становился для меня каки...      Афобазол
5   Очень рада, что в свое время решила принимать ...      Афобазол
6   На меня Афобазол производит возбуждающий эффек...      Афобазол
7   Лично мне помогает успокоиться, когда есть тре...      Афобазол
8   Достоинства: Работает. Цена ок по сравнению с ...      Афобазол
9   2 месяца назад уволили с работы по непонятной ...      Афобазол
10  Достоинства: Купила Афобазол с надеждой успоко...      Афобазол
11  Отличный безрецептурный противотревожный препа...      Афобазол
12  Достоинства: хорошо помогает, недорогой\n\nНед...      Афобазол
13  Достоинства: + Действует. Но нужно достаточно ...      Афобазол
14  Если принимать строго по инструкции и хотя бы ...      Афобазол
15  Наконец-то дошла до того, чтобы бросить курить...      Афобазол
16  Афобазол - единственный лекарственный препарат...      Афобазол
17  Иногда я принимаю Афобазол для поддержания пси...      Афобазол
18  Я довольно тяжело переживаю ПМС. За пару недел...      Афобазол
19  Достоинства: хорошо восстанавливает нервы, выр...      Афобазол
20  В наши времена без таблеток от тревоги никак. ...      Афобазол
21  Да, временами приходится спасаться именно этим...      Афобазол
22  Достоинства: успокоительный эфект есть употреб...      Афобазол
23  С такой работой как у меня без Афобазола иногд...      Афобазол
24  Достоинства: Помогает справиться, когда навали...       Авиандр
25  Не хочу никого пугать, но мне не подошел этот ...       Авиандр
26  Выписали авиандр и тералиджен, пила 2 месяца. ...       Авиандр
27  В последнее время часто была на взводе. Постоя...       Авиандр
28  Достоинства: Убирает ПА\n\nНедостатки: не выяв...       Авиандр
29  Достоинства: Помогло убрать тревожное состояни...       Авиандр
30  Достоинства: Удобно принимать, таблетки не гор...       Авиандр
31  Готовились с сыном к поступлению в институт. Д...       Авиандр
32  Достоинства: Очень помогает быть в строю\n\nНе...       Авиандр
33  Достоинства: Не нашла\n\nНедостатки: Побочка у...       Авиандр
34  Неприятности в один момент навалилось со всех ...       Авиандр
35  Достоинства: Нет\n\nНедостатки: Дорогие, не по...       Авиандр
36  После серьезного стресса постоянно пребывала в...       Авиандр
37  Достоинства: Цена очень хорошая\n\nНедостатки:...  Эсциталопрам
38  Помогает справиться с тревожностью без побочек...  Эсциталопрам
39  Недостатки: нет.\n\nКомментарий: Таблетки мне ...  Эсциталопрам
40  Назначен от болей в пояснице. После 3 месяцев ...  Эсциталопрам
41  Достоинства: быстро помогает от боли\n\nНедост...       Андипал
42  Достоинства: Андипал по адекватной цене\n\nНед...       Андипал
43  Препарат старый, и всегда в аптечке. Пью при м...       Андипал
44  Достоинства: помогает.\n\nНедостатки: неь\n\nК...       Андипал, Empty DataFrame
Columns: [comment, drag_name]
Index: [])
[2025-02-21T08:18:22.033+0000] {python.py:240} INFO - Done. Returned value was:                                               comment     drag_name
0   Достоинства: ничего\nНедостатки: почитал полож...      Афобазол
1   Достоинства: Препарат рабочий, нервы успокаива...      Афобазол
2   Достоинства: Их нет!\nНедостатки: Не помогает ...      Афобазол
3   После потери близкого человека думала сойду с ...       Авиандр
4   Пробовала разные подобные препараты, но из все...       Авиандр
5   Достоинства: Очень помог\nНедостатки: Нет\nКом...       Авиандр
0   Достоинства: Доступная цена, легко найти в люб...      Афобазол
1   Достоинства: Таблетка небольшая по форме, удоб...      Афобазол
2   Достоинства: Самое главное - действительно пом...      Афобазол
3   Хороший отечественный препарат, предназначенны...      Афобазол
4   Каждый год осенью мир становился для меня каки...      Афобазол
5   Очень рада, что в свое время решила принимать ...      Афобазол
6   На меня Афобазол производит возбуждающий эффек...      Афобазол
7   Лично мне помогает успокоиться, когда есть тре...      Афобазол
8   Достоинства: Работает. Цена ок по сравнению с ...      Афобазол
9   2 месяца назад уволили с работы по непонятной ...      Афобазол
10  Достоинства: Купила Афобазол с надеждой успоко...      Афобазол
11  Отличный безрецептурный противотревожный препа...      Афобазол
12  Достоинства: хорошо помогает, недорогой\n\nНед...      Афобазол
13  Достоинства: + Действует. Но нужно достаточно ...      Афобазол
14  Если принимать строго по инструкции и хотя бы ...      Афобазол
15  Наконец-то дошла до того, чтобы бросить курить...      Афобазол
16  Афобазол - единственный лекарственный препарат...      Афобазол
17  Иногда я принимаю Афобазол для поддержания пси...      Афобазол
18  Я довольно тяжело переживаю ПМС. За пару недел...      Афобазол
19  Достоинства: хорошо восстанавливает нервы, выр...      Афобазол
20  В наши времена без таблеток от тревоги никак. ...      Афобазол
21  Да, временами приходится спасаться именно этим...      Афобазол
22  Достоинства: успокоительный эфект есть употреб...      Афобазол
23  С такой работой как у меня без Афобазола иногд...      Афобазол
24  Достоинства: Помогает справиться, когда навали...       Авиандр
25  Не хочу никого пугать, но мне не подошел этот ...       Авиандр
26  Выписали авиандр и тералиджен, пила 2 месяца. ...       Авиандр
27  В последнее время часто была на взводе. Постоя...       Авиандр
28  Достоинства: Убирает ПА\n\nНедостатки: не выяв...       Авиандр
29  Достоинства: Помогло убрать тревожное состояни...       Авиандр
30  Достоинства: Удобно принимать, таблетки не гор...       Авиандр
31  Готовились с сыном к поступлению в институт. Д...       Авиандр
32  Достоинства: Очень помогает быть в строю\n\nНе...       Авиандр
33  Достоинства: Не нашла\n\nНедостатки: Побочка у...       Авиандр
34  Неприятности в один момент навалилось со всех ...       Авиандр
35  Достоинства: Нет\n\nНедостатки: Дорогие, не по...       Авиандр
36  После серьезного стресса постоянно пребывала в...       Авиандр
37  Достоинства: Цена очень хорошая\n\nНедостатки:...  Эсциталопрам
38  Помогает справиться с тревожностью без побочек...  Эсциталопрам
39  Недостатки: нет.\n\nКомментарий: Таблетки мне ...  Эсциталопрам
40  Назначен от болей в пояснице. После 3 месяцев ...  Эсциталопрам
41  Достоинства: быстро помогает от боли\n\nНедост...       Андипал
42  Достоинства: Андипал по адекватной цене\n\nНед...       Андипал
43  Препарат старый, и всегда в аптечке. Пью при м...       Андипал
44  Достоинства: помогает.\n\nНедостатки: неь\n\nК...       Андипал
[2025-02-21T08:18:22.230+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-21T08:18:22.231+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=consolidate_data, run_id=scheduled__2025-02-20T00:00:00+00:00, execution_date=20250220T000000, start_date=20250221T081815, end_date=20250221T081822
[2025-02-21T08:18:22.398+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-21T08:18:22.402+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-21T08:18:22.406+0000] {logging_mixin.py:190} INFO - Dag name:pipeline queued_at:2025-02-21 08:15:46.018398+00:00
[2025-02-21T08:18:22.411+0000] {logging_mixin.py:190} INFO - Task hostname:5f8091faf500 operator:_PythonDecoratedOperator
[2025-02-21T08:18:22.505+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-21T08:18:22.716+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-21T08:18:22.731+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
